# Generated by Django 4.2.3 on 2023-10-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_client_onboarddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='asignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee'),
        ),
    ]
