# Generated by Django 4.2.3 on 2023-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_employee_profile_pic_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_pic',
            field=models.ImageField(blank=True, default='companylogo.png', null=True, upload_to=''),
        ),
    ]
